### PR TITLE
(joe) update json to 2.0.2 to build on ubuntu 16.04

### PR DESCRIPTION
**Pull request by jbylund**
We're getting an issue with installing, this seems to fix, though there might be a better way:

```
gem install --no-rdoc --no-ri ./pkg/pgxn_utils-0.1.4.gem
Building native extensions.  This could take a while...
ERROR:  Error installing ./pkg/pgxn_utils-0.1.4.gem:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/json-1.6.8/ext/json/ext/generator
/usr/bin/ruby2.3 -r ./siteconf20160802-29417-vqvyr9.rb extconf.rb
creating Makefile

current directory: /var/lib/gems/2.3.0/gems/json-1.6.8/ext/json/ext/generator
make "DESTDIR=" clean
make[1]: Entering directory '/var/lib/gems/2.3.0/gems/json-1.6.8/ext/json/ext/generator'
make[1]: Leaving directory '/var/lib/gems/2.3.0/gems/json-1.6.8/ext/json/ext/generator'

current directory: /var/lib/gems/2.3.0/gems/json-1.6.8/ext/json/ext/generator
make "DESTDIR="
make[1]: Entering directory '/var/lib/gems/2.3.0/gems/json-1.6.8/ext/json/ext/generator'
compiling generator.c
In file included from generator.c:1:0:
../fbuffer/fbuffer.h: In function ‘fbuffer_to_s’:
../fbuffer/fbuffer.h:151:47: error: macro "rb_str_new" requires 2 arguments, but only 1 given
     VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                                               ^
../fbuffer/fbuffer.h:151:20: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
     VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                    ^
In file included from generator.c:2:0:
generator.c: In function ‘cState_aref’:
generator.h:96:27: warning: variable ‘state’ set but not used [-Wunused-but-set-variable]
     JSON_Generator_State *state;              \
                           ^
generator.c:632:5: note: in expansion of macro ‘GET_STATE’
     GET_STATE(self);
     ^
generator.c: In function ‘isArrayOrObject’:
generator.c:867:22: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
     return *p == '[' && *q == ']' || *p == '{' && *q == '}';
                      ^
Makefile:239: recipe for target 'generator.o' failed
make[1]: *** [generator.o] Error 1
make[1]: Leaving directory '/var/lib/gems/2.3.0/gems/json-1.6.8/ext/json/ext/generator'

make failed, exit code 2

Gem files will remain installed in /var/lib/gems/2.3.0/gems/json-1.6.8 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/json-1.6.8/gem_make.out
Makefile:3: recipe for target 'install' failed
make: *** [install] Error 1
ERROR: command returned 2: make PG_CONFIG=/usr/bin/pg_config install
```

### CODE REVIEW

**Comment by coreyatmoat** [comment]
Update multipart-post to 2.0.0 as well

**Comment by guedes** [comment]
Thanks!
